# Generated by Django 2.2.1 on 2019-06-04 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_modelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='data_modelling.Province'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='data_modelling.Customer'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='data_modelling.Residence'),
        ),
        migrations.AlterField(
            model_name='play',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='data_modelling.Director'),
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='data_modelling.Country'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='data_modelling.City'),
        ),
        migrations.AlterField(
            model_name='role',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='data_modelling.Actor'),
        ),
        migrations.AlterField(
            model_name='role',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='data_modelling.Play'),
        ),
    ]
